version: '3.8'

services: 
  backend:
    image: simbolado/bookstore-app:latest
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: simbolado/fe-book:latest
    container_name: frontend
    ports: 
      - "80:80"
    networks:
      - app-network
    environment:
      - API_URL=http://backend:8080

networks:
  app-network:
    driver: bridge
