-- Inserting sample of books
INSERT INTO book (title, isbn, publishedYear, genre, quantity, author, publisher, version, price, imageUrl, synopsis) VALUES
('The Catcher in the Rye', '9780316769488', 1951, 'Fiction', 0, 'J.D. Salinger', 'Little, Brown and Company', 0, 15.99, 'https://iili.io/dObVNSI.png', 'A novel about teenage rebellion and alienation, narrated by the unforgettable Holden Caulfield.'),
('To Kill a Mockingbird', '9780061120084', 1960, 'Fiction', 8, 'Harper Lee', 'J.B. Lippincott & Co.', 0, 18.99, 'https://iili.io/dObVwcN.png', 'A gripping, heart-wrenching tale of racial injustice in the American South.'),
('1984', '9780451524935', 1949, 'Dystopian', 10, 'George Orwell', 'Secker & Warburg', 0, 12.50, 'https://iili.io/dObg0Zl.png', 'A chilling dystopian novel that explores the dangers of totalitarianism.'),
('Moby-Dick', '9781503280786', 1851, 'Adventure', 6, 'Herman Melville', 'Harper & Brothers', 0, 17.00, 'https://iili.io/dObVXPR.png', 'An epic sea adventure about the quest to capture the elusive white whale, Moby Dick.'),
('Pride and Prejudice', '9781503290563', 1813, 'Romance', 7, 'Jane Austen', 'T. Egerton', 0, 14.75, 'https://iili.io/dObVe9t.png', 'A classic romantic comedy about manners, marriage, and society in early 19th century England.'),
('The Great Gatsby', '9780743273565', 1925, 'Tragedy', 9, 'F. Scott Fitzgerald', 'Charles Scribner''s Sons', 0, 16.20, 'https://iili.io/dObVvNn.png', 'A tragic love story and a critique of the American Dream, set in the Roaring Twenties.'),
('War and Peace', '9781400079988', 1869, 'Historical', 4, 'Leo Tolstoy', 'The Russian Messenger', 0, 20.00, 'https://iili.io/dObV8ts.png', 'A vast epic chronicling the lives of individuals and families during the Napoleonic Wars.'),
('The Fellowship Of The Ring', '9780544003415', 1954, 'Fantasy', 3, 'J.R.R. Tolkien', 'George Allen & Unwin', 0, 25.99, 'https://iili.io/dObVUoG.png', 'The first volume in the epic fantasy trilogy, The Lord of the Rings, featuring the journey of Frodo and the Fellowship.'),
('The Hobbit', '9780618968633', 1937, 'Fantasy', 6, 'J.R.R. Tolkien', 'George Allen & Unwin', 0, 19.99, 'https://iili.io/dObVgVf.png', 'A prelude to The Lord of the Rings, this is the story of Bilbo Baggins and his unexpected adventure.'),
('Catch-22', '9781451626650', 1961, 'Satire', 8, 'Joseph Heller', 'Simon & Schuster', 0, 13.50, 'https://iili.io/dObVrP4.png', 'A darkly comic novel about the absurdities of war and the contradictions of bureaucracy.');
